### ISSUE TITLE
文件存储是否支持权限管理？

### ISSUE THREAD

**Issue by csfkjs** [wildfirechat/wf-oss-gateway#1]
文件存储带权限管理嘛，比如分个人文件、部门文件、还有分人员权限，或者有没有对应控制接口

**Comment by heavyrain2012** [comment]
请参考这个说明 https://docs.wildfirechat.cn/blogs/文件存储的安全性问题.html， 主要看下载安全那里，简单的可以调用sdk的url签名方法，复杂一些的，可以自己来对url签名
